NII-cloud-operation/Jupyter-LC_wrapper

lc_wrapper.py
=> Fix incompatible types in log stream

lc_wrapper.py
=> Fix missing variables when cell_log_id are not specified

lc_wrapper.py
=> Simplify filepath encodes

lc_wrapper.py
Timezone should be decided by platform settings
=> Timezone is hard-coded as JST

README.md, lc_wrapper/__init__.py, lc_wrapper/bash/__init__.py, lc_wrapper/bash/__main__.py, lc_wrapper/bash/install.py, lc_wrapper/bash/kernel.py, lc_wrapper/ipython/__init__.py, lc_wrapper/ipython/__main__.py, lc_wrapper/ipython/install.py, lc_wrapper/ipython/kernel.py, lc_wrapper/kernel.py, setup.py
=> lc_wrapper for bash kernel

lc_wrapper/kernel.py
Add `lc_wrapper_force` variable to enable/disable the summarize mode forcefully.
If you want to enable the summarize mode on cells without `!!`, you should set `on` to `lc_wrapper_force` environment variables. Contrariwise, to disable the summarize mode on cells with `!!`, you should set `off`.
=> `lc_wrapper_force` feature

README.md, lc_wrapper/kernel.py
Allow to set the settings by the configuration file.
=> Configuring lc_wrapper by `.lc_wrapper` configuration file

lc_wrapper/kernel.py
=> Always create the log file if the summarization mode enabled

examples/Summarizing and Logging.ipynb, lc_wrapper/kernel.py
=> Fix missing execution results

lc_wrapper/kernel.py
Always show information of logs(like `path: /notebooks/.log/YYYYMMDD/xxxxxxxx-xxxxxx-xxxx.log,
start time: YYYY-MM-DD HH:mm:ss(TZ)`) when logging mode enabled. In previous version the wrapper shows it only when output is too long which should be summarized.
=> Always show information of logs when logging mode enabled

lc_wrapper/kernel.py
=> Fix symlink path

lc_wrapper/kernel.py
- Set `file:default` to `lc_wrapper_regex`
- Set `.lc_wrapper_regex.txt` to the filename of default pattern file
=> Modify message filtering feature

lc_wrapper/kernel.py
Improve the summarizer to highlight a matched word.
=> Improve keyword highlighting

lc_wrapper/kernel.py
=> Add keywords to highlight

lc_wrapper/kernel.py
Add number of logs to an execution result
=> Add number of logs to an execution result

lc_wrapper/kernel.py
=> Add `fail` to keywords

.gitignore, lc_wrapper/bash/kernel.py, lc_wrapper/ipython/kernel.py, lc_wrapper/kernel.py
Improve kernel message handling
Fix #9
=> Improve kernel message handling

lc_wrapper/kernel.py
Fix `stop_on_error` not working
Fix #35
=> Fix stop_on_error not working

lc_wrapper/kernel.py, lc_wrapper/log.py, setup.py
Add remote logging feature.
Add log messages to identify user, notebook and jupyter server.
=> Add remote logging feature

lc_wrapper/kernel.py
=> Fix missing import

lc_wrapper/kernel.py
Add waiting for idle before handling next shell message
Fix #42
=> Fix continuous execution failure

lc_wrapper/kernel.py
=> Initialize log_file_object to None

lc_wrapper/kernel.py
The `execute_reply_status` value in the log file becomes `None` if the wrapper kernel receives an `idle` message before an `execute_reply` message.
That is because the wrapper kernel closes the log file by receiving an `idle` message and it records the `execute_reply_status`  at this time.
This PR fixes the timing of closing a log file.
=> Fix the timing of closing log file

lc_wrapper/kernel.py
=> Fix the issue input_request cannot be interrupted

lc_wrapper/kernel.py
枝番実装済MEME( https://github.com/NII-cloud-operation/Jupyter-LC_nblineage/pull/15 )をサポートすするための修正です。
=> Support for MEME Enhancement

lc_wrapper/kernel.py
=> Use Thread.is_alive

.gitignore, dev-requirements.txt, lc_wrapper/kernel.py, lc_wrapper/utils.py, setup.py, tests/test_utils.py
=> Fix _abort_queues

Dockerfile, lc_wrapper/kernel.py
=> Fix interpretation of _parent_ident

README.md, lc_wrapper/__init__.py, lc_wrapper/async_kernelmanager.py
Added AsyncLCWrapperKernelManager based on AsyncIOLoopKernelManager, since LCWrapperKernelManager is based on IOLoopKernelManager and does not support asynchronous manner.
=> Add AsyncLCWrapperKernelManager

lc_wrapper/kernel.py
=> Fix interrupt not working

README.md
Add description about lc_wrapper_fluentd_host
=> Add description about lc_wrapper_fluentd_host
